server:
  port: 8080
  servlet:
    context-path: /interest
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/interest?useUnicode=true&characterEncoding=UTF-8&useSSL=false&jdbcCompliantTruncation=false&zeroDateTimeBehavior=convertToNull
    username:
    password:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    timeout: 5000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000ms
  resources:
      static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:${interest.paths-properties.image}
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.interest.model

logging:
# 你需要存储日志的目录
  file: D:/interest/file/log/interest.log
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: DEBUG
#    com.interest: DEBUG

#自定义配置
interest:
  paths-properties:
    image: D:/interest/file/image
#    image: 你需要存储图片的目录，如上
    domain-name: http://127.0.0.1:8080
#   domain-name: https://www.lovemtt.com
#   domain-name: 你的域名或者（ip+端口），如上
  github:
    client-id: 你在github中注册的client id
    client-secret: 你在github中注册的client secret
  qq:
    appid: 你在qq中注册的appid
    appkey: 你在qq中注册的appkey
  other:
#    上传文件的临时目录
    temporary-path: D:/interest/file/tmp