server:
  port: 8080
  servlet:
    context-path: /interest
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interest?useUnicode=true&characterEncoding=UTF-8&amp;useSSL=false&amp;jdbcCompliantTruncation=false&amp;zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password: null
    timeout: 5000ms
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000ms
  resources:
      static-locations:
      - classpath:/META-INF/resources/
      - classpath:/resources/
      - classpath:/static/
      - classpath:/public/
      - file:${interest.properties.paths-properties.image}
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.interest.model

logging:
  file: D:/interest/file/log/interest.log
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.interest: DEBUG

##自定义配置
interest:
  properties:
    paths-properties:
      image: D:/interest/file/image
#      domain-name: http://www.lovemtt.com/interest
      domain-name: http://127.0.0.1:8080/interest
github:
  client-id: 你在github中注册的client id
  client-secret: 你在github中注册的client secret
qq:
  aappid: 你在qq中注册的appid
  appkey: 你在qq中注册的appkey
